_base_: ./pretrain_gpt_base.yaml

Global:
  global_batch_size: 
  local_batch_size: 8
  micro_batch_size: 8


Model:
  vocab_size: 50304
  hidden_size: 5120 
  num_layers: 40 
  num_attention_heads: 40 
  ffn_hidden_size:
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 4096
  type_vocab_size: 16
  initializer_range: 0.02
  fuse_attn_qkv: True
  use_recompute: True
  recompute_granularity: 'full'
  no_recompute_layers:


Distributed:
  dp_degree:
  mp_degree: 4
  pp_degree: 2
  sharding:
    sharding_degree: 1
    sharding_stage: 1
